#page title
page_title                                : Axion Watch Guard                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6746121926                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Axion Watch Guard                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Axion Watch Guard ensures your Apple Watch and iPhone stay within reach at all times

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Onix-Systems                                
your_link                                 : https://onix-systems.com/                   
your_city                                 : Kropyvnytskyi, 76 Tarasa Karpy Street, 25006                                
email_address                             : sales@onix-systems.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title: Lost Phone Alert
    description: Your Watch vibrates the instant your iPhone drifts out of Bluetooth range.
    fontawesome_icon_name: mobile-alt

  - title: Lost Watch Alert
    description: Your iPhone buzzes the moment your Watch is left behind.
    fontawesome_icon_name: watch

  - title: Play Sound
    description: Trigger a loud ring on your missing device with one tap—ideal for finding it under cushions, in bags or between car seats.
    fontawesome_icon_name: volume-up

  - title: Route Finder
    description: Open a map showing exact distance and direction from Watch → iPhone (or iPhone → Watch) so you can retrace your steps.
    fontawesome_icon_name: map-marked-alt

  - title: Signal-Strength Monitor
    description: Watch live Bluetooth bars grow or shrink as you move closer or farther from your device—no guesswork needed.
    fontawesome_icon_name: signal

  - title: Custom Distance Alerts
    description: Choose your own separation threshold (5 ft, 10 ft, 20 ft or any distance you prefer) and get warned exactly when it matters.
    fontawesome_icon_name: ruler-horizontal

  - title: Loud Alarm
    description: Enable an extra-powerful tone to guarantee you never miss a lost-device notification, even in noisy environments.
    fontawesome_icon_name: bell


  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#233EE3"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
